pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./01_id_posts_in_board.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./02_keyword_posts_in_board.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./03_post_id_count.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./04_post_keyword.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./05_account_checker.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./06_account_checker_with_geolocation.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "./07_vote_checker.py"