pyinstaller --noconfirm --onefile --console --no-embed-manifest  "C:/Users/t0336/Documents/projects/ptt-task-helper/01_id_posts_in_board.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "C:/Users/t0336/Documents/projects/ptt-task-helper/02_keyword_posts_in_board.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "C:/Users/t0336/Documents/projects/ptt-task-helper/03_post_id_count.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "C:/Users/t0336/Documents/projects/ptt-task-helper/04_post_keyword.py"
pyinstaller --noconfirm --onefile --console --no-embed-manifest  "C:/Users/t0336/Documents/projects/ptt-task-helper/05_account_checker.py"